 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '0 0 1 */6 *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: jasineri/gitartwork@v1
         with:
            token: ${{ secrets.GH_TOKEN }}
            # Use this username's contribution graph  
            user_name: aayush-rajpara
            # Text on contribution graph 
            text: AAYUSH
       - uses: jasineri/simple-push-action@v1
